{{- if and .Values.dataplane.enabled (gt (int .Values.dataplane.replicas) 1) }}
{{- $ns := include "nantian-gw.namespace" . }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nantian-gw.name" . }}-dataplane
  namespace: {{ $ns }}
  labels:
    {{- include "nantian-gw.dataplane.labels" . | nindent 4 }}
spec:
  {{- if .Values.dataplane.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.dataplane.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.dataplane.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nantian-gw.dataplane.selectorLabels" . | nindent 6 }}
{{- end }}