apiVersion: v2
name: nantian-gw
description: Nantian Gateway - Kubernetes Gateway API implementation with Go control plane and Rust/Nantian data plane
type: application
version: 0.2.3
appVersion: "0.1.0"
keywords:
  - gateway
  - gateway-api
  - nantian
  - rust
  - kubernetes
home: https://github.com/nantian-gw/gateway
sources:
  - https://github.com/nantian-gw/gateway
maintainers:
  - name: Nantian Gateway Maintainers
dependencies:
  - name: gateway-api-crds-standard
    version: 0.1.0
    repository: "file://./charts/gateway-api-crds-standard"
    condition: gatewayAPI.installCRDs
