featureMode: standard

gatewayAPI:
  installCRDs: false
  channel: standard

controlplane:
  replicas: 2
  image:
    tag: "sha-8737dc3"
    pullPolicy: IfNotPresent

dataplane:
  replicas: 2
  image:
    tag: "sha-9670107"
    pullPolicy: IfNotPresent

dashboard:
  enabled: true
  image:
    tag: "sha-af29925"
    pullPolicy: IfNotPresent
  ingress:
    enabled: false

networkPolicies:
  enabled: true

certs:
  generate: false
  certManager:
    enabled: false
