{{- if .Values.certs.certManager.enabled }}
{{- $ns := include "nantian-gw.namespace" . }}
{{- $name := include "nantian-gw.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}-grpc-server-tls
  namespace: {{ $ns }}
  labels: {{- include "nantian-gw.labels" . | nindent 4 }}
spec:
  secretName: {{ $name }}-grpc-server-tls
  issuerRef:
    name: {{ required "certs.certManager.issuerRef.name is required" .Values.certs.certManager.issuerRef.name }}
    kind: {{ .Values.certs.certManager.issuerRef.kind | default "Issuer" }}
  commonName: "{{ $name }}-controlplane"
  dnsNames:
    - "{{ $name }}-controlplane"
    - "{{ $name }}-controlplane.{{ $ns }}.svc"
    - "{{ $name }}-controlplane.{{ $ns }}.svc.cluster.local"
  usages:
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}-grpc-client-tls
  namespace: {{ $ns }}
  labels: {{- include "nantian-gw.labels" . | nindent 4 }}
spec:
  secretName: {{ $name }}-grpc-client-tls
  issuerRef:
    name: {{ required "certs.certManager.issuerRef.name is required" .Values.certs.certManager.issuerRef.name }}
    kind: {{ .Values.certs.certManager.issuerRef.kind | default "Issuer" }}
  commonName: "{{ $name }}-dataplane"
  usages:
    - client auth
{{- end }}
