{{- if .Values.hpa.enabled }}
{{- $ns := include "nantian-gw.namespace" . }}
{{- if .Values.dataplane.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nantian-gw.name" . }}-dataplane
  namespace: {{ $ns }}
  labels:
    {{- include "nantian-gw.dataplane.labels" . | nindent 4 }}
    gateway.nantian.dev/addon: dataplane-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nantian-gw.name" . }}-dataplane
  minReplicas: {{ .Values.hpa.dataplane.minReplicas }}
  maxReplicas: {{ .Values.hpa.dataplane.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetMemoryUtilization }}
{{- end }}
{{- if .Values.controlplane.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nantian-gw.name" . }}-controlplane
  namespace: {{ $ns }}
  labels:
    {{- include "nantian-gw.controlplane.labels" . | nindent 4 }}
    gateway.nantian.dev/addon: controlplane-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nantian-gw.name" . }}-controlplane
  minReplicas: {{ .Values.hpa.controlplane.minReplicas }}
  maxReplicas: {{ .Values.hpa.controlplane.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetMemoryUtilization }}
{{- end }}
{{- end }}
