{{- if .Values.controlplane.enabled }}
{{- $ns := include "nantian-gw.namespace" . }}
{{- $cpName := include "nantian-gw.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $cpName }}-controlplane-grpc
  namespace: {{ $ns }}
  labels:
    {{- include "nantian-gw.controlplane.labels" . | nindent 4 }}
    gateway.nantian.dev/service-role: grpc
spec:
  selector:
    {{- include "nantian-gw.controlplane.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 18080
      targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $cpName }}-controlplane-admin
  namespace: {{ $ns }}
  labels:
    {{- include "nantian-gw.controlplane.labels" . | nindent 4 }}
    gateway.nantian.dev/service-role: admin
spec:
  selector:
    {{- include "nantian-gw.controlplane.selectorLabels" . | nindent 4 }}
  ports:
    - name: admin
      port: 18081
      targetPort: admin
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $cpName }}-controlplane-metrics
  namespace: {{ $ns }}
  labels:
    {{- include "nantian-gw.controlplane.labels" . | nindent 4 }}
    gateway.nantian.dev/service-role: metrics
spec:
  selector:
    {{- include "nantian-gw.controlplane.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 18082
      targetPort: metrics
{{- end }}