{{- if .Values.controlplane.enabled }}
{{- $ns := include "nantian-gw.namespace" . }}
{{- $cpName := include "nantian-gw.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $cpName }}-controlplane
  namespace: {{ $ns }}
  labels:
    {{- include "nantian-gw.controlplane.labels" . | nindent 4 }}
    gateway.nantian.dev/service-role: controlplane
spec:
  selector:
    {{- include "nantian-gw.controlplane.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 18080
      targetPort: grpc
    - name: admin
      port: 18081
      targetPort: admin
    - name: metrics
      port: 18082
      targetPort: metrics
{{- end }}
